import { afterEach, describe, expect, it, vi } from 'vitest';
import { HostBridge, importFile, safePreviewUrl } from '../src/bridge';
import { applyEvent, ChatStore, type State } from '../src/store';
import type { Bootstrap, HostEvent, Rpc, Session, Task } from '../src/types';
const session=(id:string,readOnly=false):Session=>({id,title:id,readOnly,created:'',updated:'',draft:'',scroll:0});
const boot:Bootstrap={sessions:[session('a'),session('b'),session('legacy:old')],settings:{api:{},local:{},preferences:{},analysis:{},alignment:{}},tasks:[],host:{name:'test',version:'1',cloudAllowed:false},models:[],providers:[]};
function adapter(extra:Record<string,(p:any)=>unknown>={}){return vi.fn(async(method:string,params:any)=>{if(extra[method])return await extra[method](params);if(method==='bootstrap')return structuredClone(boot);if(method==='sessions.get')return {session:session(params.sessionId),messages:[]};if(method==='events.poll')return {events:[],cursor:0};return {ok:true};});}
afterEach(()=>{delete window.pywebview;vi.useRealTimers();});
describe('restricted bridge',()=>{
  it('fails closed with no host; never supplies a fake bootstrap',async()=>{const bridge=new HostBridge();await expect(bridge.rpc('bootstrap',{})).rejects.toThrow('未连接');await expect(bridge.wait(5)).rejects.toThrow('不会模拟后端');});
  it('waits for pywebviewready and binds only api.rpc',async()=>{const bridge=new HostBridge();const wait=bridge.wait(1000);const rpc=vi.fn(async()=>structuredClone(boot));window.pywebview={api:{rpc}};window.dispatchEvent(new Event('pywebviewready'));await wait;await bridge.rpc('bootstrap',{});expect(rpc).toHaveBeenCalledExactlyOnceWith('bootstrap',{});});
  it('rejects arbitrary methods and executable links before calling host',async()=>{const rpc=adapter();const bridge=new HostBridge(rpc as Rpc);await expect(bridge.rpc('links.open',{url:'javascript:alert(1)'})).rejects.toThrow('HTTP');await expect((bridge.rpc as any)('exec',{script:'x'})).rejects.toThrow('白名单');expect(rpc).not.toHaveBeenCalled();});
  it('imports bounded UTF-8 file as Base64 using exact contract',async()=>{const rpc=adapter({'attachments.import':p=>({id:'file',name:p.name,mime:p.mime,size:3})});await importFile(rpc as Rpc,new File(['声'],'声音.txt',{type:'text/plain'}));const args=rpc.mock.calls[0];expect(args[0]).toBe('attachments.import');expect(args[1]).toEqual({name:'声音.txt',mime:'text/plain',data:'5aOw'});expect(JSON.stringify(args)).not.toContain('path');});
  it('rejects oversized data before import and unsafe preview mime',async()=>{const rpc=adapter();const file=new File(['x'],'large.wav');Object.defineProperty(file,'size',{value:21*1024*1024});await expect(importFile(rpc as Rpc,file)).rejects.toThrow('20 MB');expect(rpc).not.toHaveBeenCalled();expect(safePreviewUrl('data:image/svg+xml;base64,PHN2Zz4=')).toBeUndefined();expect(safePreviewUrl('data:text/html;base64,YQ==')).toBeUndefined();expect(safePreviewUrl('data:image/png;base64,YQ==')).toBeTruthy();});
});
describe('task/session isolation and durable view adapter',()=>{
  const initial:State={sessions:boot.sessions,messages:{a:[],b:[]},tasks:{},loading:{},submitting:{},selected:'b',connected:true};
  it('projects background text to event session, not selected session',()=>{const e:HostEvent={seq:1,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:'后台'}};const next=applyEvent(initial,e);expect(next.messages.a[0].content).toBe('后台');expect(next.messages.b).toEqual([]);expect(next.selected).toBe('b');});
  it('keeps execution facts through authoritative activity replacements',()=>{let s=applyEvent(initial,{seq:1,sessionId:'a',taskId:'ta',type:'activity',payload:{messageId:'ma',activity:{id:'tool',type:'tool',status:'running',execution:'已投递'}}});s=applyEvent(s,{seq:2,sessionId:'a',taskId:'ta',type:'activity',payload:{messageId:'ma',activity:{id:'tool',type:'tool',status:'cancelled',execution:'执行状态不明',result:{source:'Praat'}}}});expect(s.messages.a[0].activities).toHaveLength(1);expect(s.messages.a[0].activities![0].execution).toBe('执行状态不明');});
  it('refuses a task whose event claims another session',()=>{const task:Task={id:'t',sessionId:'a',status:'running',model:'m',created:''};const s={...initial,tasks:{t:task}};expect(applyEvent(s,{seq:1,sessionId:'b',taskId:'t',type:'delta',payload:{messageId:'m',text:'wrong'}})).toBe(s);});
  it('switching preserves independent drafts and does not cancel',async()=>{vi.useFakeTimers();const rpc=adapter();const store=new ChatStore(rpc as Rpc);await store.initialize();store.view('a',{draft:'甲',scroll:123});await store.select('b');store.view('b',{draft:'乙',scroll:456});await vi.advanceTimersByTimeAsync(500);expect(store.getSnapshot().sessions.find(s=>s.id==='a')?.draft).toBe('甲');expect(rpc.mock.calls.filter(([m])=>m==='tasks.cancel')).toHaveLength(0);expect(rpc.mock.calls.filter(([m])=>m==='sessions.view').map(([,p])=>p)).toEqual([{sessionId:'a',draft:'甲',scroll:123},{sessionId:'b',draft:'乙',scroll:456}]);store.stop();});
  it('rejects legacy edits even if readOnly is falsely omitted',async()=>{const rpc=adapter();const store=new ChatStore(rpc as Rpc);await store.initialize();await expect(store.submit('legacy:old','x',[])).rejects.toThrow('旧记录');await expect(store.rename('legacy:old','x')).rejects.toThrow('只读');expect(rpc.mock.calls.filter(([m])=>m.startsWith('tasks.'))).toHaveLength(0);store.stop();});
  it('guards same-session overlap while allowing another session',async()=>{let resolve!:(t:Task)=>void;const pending=new Promise<Task>(r=>resolve=r);const rpc=adapter({'tasks.submit':p=>p.sessionId==='a'?pending:{id:'tb',sessionId:'b',status:'running',model:'b-model',created:''}});const store=new ChatStore(rpc as Rpc);await store.initialize();const first=store.submit('a','first',[]);await expect(store.submit('a','duplicate',[])).rejects.toThrow('本会话');await store.submit('b','parallel',[]);resolve({id:'ta',sessionId:'a',status:'running',model:'a-model',created:''});await first;await store.cancel('a');expect(rpc).toHaveBeenCalledWith('tasks.cancel',{taskId:'ta'});expect(store.running('b')?.id).toBe('tb');store.stop();});
  it('does not retry failed submissions and recovers the draft',async()=>{const rpc=adapter({'tasks.submit':()=>{throw new Error('投递状态不明');}});const store=new ChatStore(rpc as Rpc);await store.initialize();await expect(store.submit('a','原始草稿',[])).rejects.toThrow('投递状态');expect(rpc.mock.calls.filter(([m])=>m==='tasks.submit')).toHaveLength(1);expect(store.getSnapshot().sessions[0].draft).toBe('原始草稿');expect(store.getSnapshot().error).toContain('未自动重试');store.stop();});
  it('refreshes loaded background histories on cursor reset',async()=>{const rpc=adapter({'events.poll':()=>({events:[],cursor:40,reset:true})});const store=new ChatStore(rpc as Rpc);await store.initialize();await store.load('b');await store.pollOnce();expect(rpc.mock.calls.filter(([m])=>m==='bootstrap')).toHaveLength(2);expect(rpc.mock.calls.filter(([m,p])=>m==='sessions.get'&&p.sessionId==='b')).toHaveLength(2);store.stop();});
  it('duplicate poll sequence is ignored and authoritative final text replaces partial',async()=>{let n=0;const events:HostEvent[]=[{seq:1,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:'one'}},{seq:2,sessionId:'a',taskId:'ta',type:'message',payload:{id:'ma',role:'assistant',taskId:'ta',content:'final',status:'complete'}}];const rpc=adapter({'events.poll':()=>({events:n++?events:[events[0]],cursor:n===1?1:2})});const store=new ChatStore(rpc as Rpc);await store.initialize();await store.pollOnce();await store.pollOnce();expect(store.getSnapshot().messages.a[0].content).toBe('final');store.stop();});
  it('does not append polled deltas already contained in an active snapshot',async()=>{
    const task:Task={id:'ta',sessionId:'a',status:'running',model:'m',created:''};let n=0;
    const rpc=adapter({'bootstrap':()=>({...structuredClone(boot),tasks:[task]}),'sessions.get':p=>({session:session(p.sessionId),messages:[{id:'ma',role:'assistant',taskId:'ta',status:'running',content:n?'already+new':'already'}]}),'events.poll':()=>({events:[{seq:++n,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:n===1?'already':'+new'}}],cursor:n})});
    const store=new ChatStore(rpc as Rpc);await store.initialize();await store.pollOnce();await store.pollOnce();expect(store.getSnapshot().messages.a[0].content).toBe('already+new');expect(rpc.mock.calls.filter(([m])=>m==='sessions.get')).toHaveLength(3);store.stop();
  });
  it('ignores message creation and deltas older than the snapshot watermark', async()=>{
    const task:Task={id:'ta',sessionId:'a',status:'running',model:'m',created:''};
    const rpc=adapter({'sessions.get':p=>({session:session(p.sessionId),cursor:3,messages:[{id:'ma',role:'assistant',taskId:'ta',status:'running',content:'live'}]}),'events.poll':()=>({cursor:4,events:[{seq:1,sessionId:'a',taskId:'ta',type:'message',payload:{id:'ma',role:'assistant',taskId:'ta',status:'running',content:''}},{seq:2,sessionId:'a',taskId:'ta',type:'task',payload:task},{seq:3,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:'live'}},{seq:4,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:'+next'}}]})});
    const store=new ChatStore(rpc as Rpc);await store.initialize();await store.pollOnce();
    expect(store.getSnapshot().messages.a[0].content).toBe('live+next');expect(store.running('a')?.id).toBe('ta');store.stop();
  });
  it('replays only post-watermark deltas while a snapshot RPC is pending', async()=>{
    let resolve!:(value:any)=>void;let loads=0;
    const rpc=adapter({'sessions.get':p=>++loads===1?{session:session(p.sessionId),cursor:0,messages:[]}:new Promise(r=>resolve=r),'events.poll':()=>({cursor:2,events:[{seq:1,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:'live'}},{seq:2,sessionId:'a',taskId:'ta',type:'delta',payload:{messageId:'ma',text:'+next'}}]})});
    const store=new ChatStore(rpc as Rpc);await store.initialize();const loading=store.load('a');await store.pollOnce();
    resolve({session:session('a'),cursor:1,messages:[{id:'ma',role:'assistant',taskId:'ta',status:'running',content:'live'}]});await loading;
    expect(store.getSnapshot().messages.a[0].content).toBe('live+next');store.stop();
  });
});
