import { test, expect } from '@playwright/test';
import { join } from 'node:path';
test('Pi-style status, numbers, popover dismissal, model and strength changes', async ({page}) => {
  const errors:string[]=[];page.on('pageerror', e=>errors.push(e.message));
  await page.goto('/?demo=1');
  const context=page.getByRole('button',{name:'上下文用量'});
  const model=page.getByRole('button',{name:'切换模型与推理强度'});
  await expect(context).toContainText('%');
  await expect(page.locator('.editor-toolbar small')).toHaveCount(0);
  await expect(page.locator('.composer-actions>small')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'加粗（Ctrl+B）'})).toBeVisible();
  const c=await context.boundingBox(), m=await model.boundingBox(), send=await page.getByRole('button',{name:'发送消息'}).boundingBox();
  expect(c!.x+c!.width).toBeLessThanOrEqual(m!.x);expect(m!.x+m!.width).toBeLessThanOrEqual(send!.x);
  await context.click();
  const details=page.getByRole('dialog',{name:'上下文用量详情'});
  await expect(details).toBeVisible();await expect(details).toContainText('估算');
  await expect(details).toContainText('32,768');await expect(details).toContainText('输出预留');
  await expect.poll(async()=>{const d=await details.boundingBox();return d!.y+d!.height;}).toBeLessThan(c!.y);
  if(process.env.PI_SCRATCH_DIR)await page.screenshot({path:join(process.env.PI_SCRATCH_DIR,'composer-context-demo.png')});
  await page.keyboard.press('Escape');await expect(details).toBeHidden();
  await context.click();await page.locator('.chat-header h1').click();await expect(details).toBeHidden();
  await model.click();const popup=page.getByRole('dialog',{name:'模型与推理强度'});
  await expect(popup).toBeVisible();await expect(page.getByRole('textbox',{name:'搜索或输入模型名'})).toBeFocused();
  await popup.getByRole('button',{name:'高',exact:true}).click();await expect(model).toContainText(' · high');
  const query=page.getByRole('textbox',{name:'搜索或输入模型名'});await query.fill('custom-fixture');
  await popup.getByRole('option').filter({hasText:'custom-fixture'}).click();await expect(model).toContainText('custom-fixture · high');
  await expect(popup).toContainText('仅用于后续任务');
  if(process.env.PI_SCRATCH_DIR)await page.screenshot({path:join(process.env.PI_SCRATCH_DIR,'composer-model-demo.png')});
  await page.keyboard.press('Escape');await expect(popup).toBeHidden();
  await page.getByRole('button',{name:'打开设置'}).click();
  await expect(page.getByLabel('API Key',{exact:true})).toHaveValue('');
  await expect(page.getByText('已保存凭据（不可读取）。留空保存会保留原 Key。',{exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});
test('compact dark layout and context updates from draft/attachments',async({page})=>{
  await page.setViewportSize({width:390,height:740});await page.goto('/?demo=1');
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');
  const context=page.getByRole('button',{name:'上下文用量'});await expect(context).toContainText('%');
  await context.click();const details=page.getByRole('dialog',{name:'上下文用量详情'});
  await expect(details).toBeVisible();
  const box=await details.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(390);expect(box!.y).toBeGreaterThanOrEqual(0);
  const before=await details.locator('.context-values dd').first().innerText();await page.keyboard.press('Escape');
  await page.getByRole('textbox',{name:'消息输入'}).fill('草稿材料'.repeat(400));
  await page.getByRole('button',{name:'添加附件'}).click();
  await expect(context).toContainText('%');await context.click();await expect(details.locator('.context-values dd').first()).not.toHaveText(before);
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'切换模型与推理强度'}).click();
  const popup=page.getByRole('dialog',{name:'模型与推理强度'});await expect(popup).toBeVisible();
  const p=await popup.boundingBox();expect(p!.x).toBeGreaterThanOrEqual(0);expect(p!.x+p!.width).toBeLessThanOrEqual(390);
  if(process.env.PI_SCRATCH_DIR)await page.screenshot({path:join(process.env.PI_SCRATCH_DIR,'composer-narrow-dark-demo.png')});
});
