import { useState } from 'react';
import { ArrowLeft, AudioLines, Brain, Database, Eye, EyeOff, Layers, Palette, Server, ShieldCheck } from 'lucide-react';
import { knownModel, type Bootstrap, type Config, type Settings, type TestResult } from './types';
import { ChatStore, useChatState } from './store';
import { IconButton, Json, Modal } from './ui';
const categories = [ ['模型', Server], ['上下文与输出', Layers], ['采样与思考', Brain], ['Praat 工具与音频', AudioLines], ['外观与交互', Palette], ['会话与存储', Database] ] as const;
export const redactSettings = (settings: Settings): Settings => ({...settings, api: {...settings.api, api_key: '', clear_api_key: false}, local: {...settings.local, api_key: ''}});
export const settingsIdentity = (settings: Settings) => JSON.stringify(settings); // memory only; never shown or persisted
function Field({config, name, label, update, kind = 'text', choices, hint, min, max, step}: {config: Config; name: string; label: string; update: (name: string, value: unknown) => void; kind?: string; choices?: string[]; hint?: string; min?: number; max?: number; step?: number}) {
  const value = config[name];
  return <label className={`field ${kind === 'checkbox' ? 'toggle-field' : ''}`}><span>{label}</span>{kind === 'checkbox' ? <input aria-label={label} type="checkbox" checked={Boolean(value)} onChange={e => update(name, e.target.checked)} /> : choices ? <select aria-label={label} value={String(value ?? '')} onChange={e => update(name, e.target.value)}><option value="" disabled>未设置 / 保留原值</option>{choices.map(v => <option key={v} value={v}>{({auto: '自动', manual: '手动', provider: '服务商决定', system: '跟随系统', dark: '深色', light: '浅色', enter: 'Enter 发送', 'ctrl-enter': 'Ctrl / ⌘ + Enter 发送'} as Record<string, string>)[v] || v}</option>)}</select> : <input aria-label={label} type={kind} value={typeof value === 'number' || typeof value === 'string' ? value : ''} placeholder="未设置 · 模型 / 宿主默认" min={min} max={max} step={step} onChange={e => { const v = e.target.value; update(name, kind === 'number' ? (v === '' ? null : Number(v)) : v); }} />}{hint && <small>{hint}</small>}</label>;
}
function RangeField(props: Parameters<typeof Field>[0]) {
  const value = props.config[props.name];
  return <div className="range-field"><Field {...props} kind="number"/><input aria-label={`${props.label}滑条`} type="range" min={props.min} max={props.max} step={props.step} disabled={typeof value !== 'number'} value={typeof value === 'number' ? value : props.min} onChange={e => props.update(props.name, Number(e.target.value))} /></div>;
}
export function SettingsDashboard({store, onClose}: {store: ChatStore; onClose: () => void}) {
  const state = useChatState(store); const boot = state.boot!;
  const [settings, setSettings] = useState<Settings>(() => redactSettings(boot.settings));
  const [category, setCategory] = useState('模型'); const [scope, setScope] = useState<'api'|'local'>('api');
  const [showKey, setShowKey] = useState(false); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState('');
  const [results, setResults] = useState<Partial<Record<'text'|'audio', {identity: string; result: TestResult}>>>({});
  const [confirmTest, setConfirmTest] = useState<'text'|'audio'>(); const [confirmClose, setConfirmClose] = useState(false);
  const dirty = settingsIdentity(settings) !== settingsIdentity(redactSettings(boot.settings));
  const update = (section: keyof Settings) => (name: string, value: unknown) => setSettings(s => ({...s, [section]: {...s[section] as Config, [name]: value}}));
  const config = settings[scope]; const change = update(scope);
  const field = (name: string, label: string, kind = 'text', hint?: string, choices?: string[]) => <Field key={name} config={config} name={name} label={label} update={change} kind={kind} hint={hint} choices={name === 'provider' ? choices?.map(v => v === 'openai' ? 'api' : v) : name === 'thinking_level' ? choices?.filter(v => v !== 'deep') : choices}/>;
  const targetUrl = String(settings.api.enabled ? settings.api.base_url || '' : settings.local.base_url || '');
  const remote = !/^https?:\/\/(localhost|127\.0\.0\.1|\[::1\])(?::\d+)?(?:\/|$)/i.test(targetUrl);
  const requestTest = (kind: 'text'|'audio') => { if (remote) setConfirmTest(kind); else void runTest(kind); };
  async function runTest(kind: 'text'|'audio') {
    setConfirmTest(undefined); setBusy(kind); setNotice('');
    const snapshot = structuredClone(settings); const identity = settingsIdentity(snapshot);
    try { const result = await store.rpc('settings.test', {kind, settings: snapshot}); setResults(r => ({...r, [kind]: {identity, result}})); }
    catch (e) { setResults(r => ({...r, [kind]: {identity, result: {status: 'failed', reason: e instanceof Error ? e.message : String(e)}}})); }
    finally { setBusy(''); }
  }
  async function save() {
    setBusy('save'); setNotice('');
    try { const result = await store.save(settings); setSettings(redactSettings(result)); setNotice('设置已保存。运行中任务保持启动时配置；新配置用于新任务。'); }
    catch (e) { store.report(e); } finally { setBusy(''); }
  }
  const resultCard = (kind: 'text'|'audio') => {
    const entry = results[kind]; const stale = entry && entry.identity !== settingsIdentity(settings);
    return <div className="test-result"><h4>{kind === 'text' ? '文字连接' : '音频能力'} <span className="badge">{busy === kind ? '验证中' : stale ? '配置已更改' : entry?.result.status || '未测试'}</span></h4><p>{stale ? '结果属于先前配置，请重新验证。' : entry?.result.reason || '只有点击对应测试后才会发送最小验证请求。未测试不代表支持。'}</p>{entry && <details><summary>诊断详情{stale ? '（旧配置）' : ''}</summary><Json value={entry.result}/></details>}</div>;
  };
  return <section className="settings-dashboard" aria-label="设置仪表盘"><nav className="settings-nav" aria-label="设置分类"><button className="back-button" onClick={() => dirty ? setConfirmClose(true) : onClose()}><ArrowLeft size={17}/>返回聊天</button><h2>设置</h2>{categories.map(([label, Icon]) => <button key={label} aria-current={category === label ? 'page' : undefined} className={category === label ? 'selected' : ''} onClick={() => setCategory(label)}><Icon size={18}/>{label}</button>)}<div className="settings-host"><ShieldCheck size={18}/><small>{boot.host.name} {boot.host.version}<br/>{boot.host.cloudAllowed ? '宿主允许显式云端请求' : '云端请求未获授权'}</small></div></nav><div className="settings-main"><header><div><span className="eyebrow">工作空间 / 设置</span><h1>{category}</h1></div><button className="primary" disabled={Boolean(busy)} onClick={() => void save()}>{busy === 'save' ? '保存中…' : dirty ? '保存更改' : '保存设置'}</button></header>{notice && <p role="status" className="notice">{notice}</p>}
    {['模型', '上下文与输出', '采样与思考'].includes(category) && <div className="segmented" aria-label="参数配置范围"><button aria-pressed={scope === 'api'} onClick={() => setScope('api')}>云端 API</button><button aria-pressed={scope === 'local'} onClick={() => setScope('local')}>本地模型</button><small>分别保存 · 不影响其他任务</small></div>}
    {category === '模型' && <><section className="card"><h3>连接配置</h3><p className="muted">前端只通过桌面宿主连接模型，不直接请求任何服务商。</p>{scope === 'api' && <><Field config={settings.api} name="enabled" label="启用云端 API" kind="checkbox" update={(n,v) => { if (!v && settings.api.locked) { setNotice('云端 API 已锁定，请先解除锁定再切换本地。'); return; } update('api')(n,v); }}/><label className="field"><span>服务商预设</span><select aria-label="服务商预设" value={String(settings.api.label || '')} onChange={e => { const provider = boot.providers.find(p => p.label === e.target.value); setSettings(s => ({...s, api: {...s.api, label: e.target.value, ...(provider ? {base_url: provider.base_url, model: provider.model} : {})}})); }}><option value="">自定义服务商</option>{boot.providers.map(p => <option key={p.label}>{p.label}</option>)}</select><small>{boot.providers.find(p => p.label === settings.api.label)?.hint || '可以自定义下方全部连接字段'}</small></label>{field('label', '服务商名称')}</>}{field('base_url', 'API 地址', 'url')}{field('model', '模型名')}{scope === 'api' && <div className="key-row"><Field config={settings.api} name="api_key" label="API Key" kind={showKey ? 'text' : 'password'} update={update('api')} hint={settings.api.has_api_key ? '已保存凭据（不可读取）。留空保存会保留原 Key。' : '凭据仅瞬时保存在输入中；不会写入浏览器存储。'}/><IconButton label={showKey ? '隐藏 API Key' : '显示 API Key'} onClick={() => setShowKey(s => !s)}>{showKey ? <EyeOff size={18}/> : <Eye size={18}/>}</IconButton></div>}{scope === 'api' && field('clear_api_key', '显式清除已保存 API Key', 'checkbox', '保存后清除；留空输入不会清除。')}{field('request_timeout_sec', '请求超时（秒）', 'number')}{scope === 'local' && <>{field('provider', '本地客户端类型', 'text', undefined, ['llama.cpp', 'ollama', 'openai'])}{field('default_mode', '默认输入模式', 'text', undefined, ['text', 'audio'])}{field('keep_alive_sec', '保活时间（秒）', 'number')}</>}</section>{scope === 'api' && <section className="card"><h3>连接策略</h3>{field('locked', '锁定云端 API', 'checkbox', '防止切回本地模型；不改写运行中的任务。')}{field('stop_local_service', '启用 API 时停止本机模型服务', 'checkbox', '由宿主按资源占用调度；不能卸载其他任务在用的服务。')}{field('use_world_knowledge', '允许使用自身知识', 'checkbox', '可以解释与举例；测量数字仍只能来自工具结果。')}{field('audio_input_enabled', '启用直接音频输入', 'checkbox', '未知能力时请单独验证，开关不代表模型支持。')}<small>音频来源：{String(settings.api.audio_input_source || 'unknown')} · {String(settings.api.audio_input_reason || '宿主未提供能力结论')}</small></section>}<section className="card"><h3>独立验证</h3><p className="muted">测试使用此页面的当前配置，文字连接和音频能力分别验证。不会在加载或保存时自动调用。</p>{remote && !boot.host.cloudAllowed && <p className="warning">宿主未授权云端。请经授权以 --allow-cloud 启动；前端不能提升权限。</p>}<div className="actions"><button disabled={Boolean(busy) || (remote && !boot.host.cloudAllowed)} onClick={() => requestTest('text')}>测试文字连接</button><button disabled={Boolean(busy) || (remote && !boot.host.cloudAllowed)} onClick={() => requestTest('audio')}>验证音频能力</button></div><div className="result-grid">{resultCard('text')}{resultCard('audio')}</div></section></>}
    {category === '上下文与输出' && <><section className="card"><h3>Token 预算</h3>{field('token_mode', 'Token 模式', 'text', undefined, ['auto', 'manual', 'provider'])}{config.token_mode === 'provider' && <p className="notice">项目不额外施加输出上限。不等于使用模型最大能力；压缩仍需要下方真实上下文窗口。</p>}{['manual','provider'].includes(String(config.token_mode)) ? <><RangeField config={config} name="max_context_tokens" label="上下文 token" update={change} min={1024} max={2000000} step={256}/>{config.token_mode === 'manual' && <RangeField config={config} name="plan_max_tokens" label="回复 token 上限" update={change} min={128} max={200000} step={128}/>}</> : <ModelCapability boot={boot} config={config} onManual={() => change('token_mode','manual')}/>}</section><section className="card"><h3>上下文压缩与专业证据</h3><p>三种模式均由宿主按真实窗口在接近满载时压缩。保留近期消息、任务目标、原始记录及结构化证据；摘要不替代测量事实。</p><p className="muted">此契约没有手动压缩或清空上下文 RPC，因此不会显示虚假的“压缩完成”按钮。真实压缩事件显示在聊天执行过程内。</p></section></>}
    {category === '采样与思考' && <><section className="card"><h3>采样参数</h3><p className="muted">保留用户原值；留空表示未设置，不强加统一默认值。参数支持性未知，宿主应校验并报告不支持字段。</p><RangeField config={config} name="plan_temperature" label="Temperature" update={change} min={0} max={2} step={0.01}/><RangeField config={config} name="top_p" label="Top P" update={change} min={0} max={1} step={0.01}/><RangeField config={config} name="presence_penalty" label="Presence penalty" update={change} min={-2} max={2} step={0.01}/></section><section className="card"><h3>思考</h3>{field('thinking_level','思考档位','text','具体档位由当前模型支持能力决定；不生成虚构思考。',['auto','off','low','medium','high','deep'])}{scope === 'api' ? field('force_deep_thinking','强制深度思考','checkbox') : field('enable_thinking','启用本地思考','checkbox')}<p className="muted">当前修改仅针对{scope === 'api' ? '云端' : '本地'}配置。界面只展示后端实际提供的思考内容。</p></section></>}
    {category === 'Praat 工具与音频' && <><section className="card"><h3>工具安全边界</h3><p>全局串行执行 · 对象与范围校验 · 工具白名单 · 结构化证据</p><p className="warning">取消不代表撤销已执行操作。投递状态不明时不得重复提交；请在桌面确认状态后处理。</p><Field config={settings.local} name="audio_input_enabled" label="本地直接音频输入" kind="checkbox" update={update('local')}/><Field config={settings.local} name="vision_when_requested" label="请求时启用视觉输入" kind="checkbox" update={update('local')}/></section><section className="card"><h3>声学分析</h3>{[['default_error_threshold','默认误差阈值'],['minimum_error_duration_sec','最短误差时长（秒）'],['maximum_errors_per_phone','每音素最大误差数量']].map(([name,label]) => <Field key={name} config={settings.analysis} name={name} label={label} kind="number" update={update('analysis')}/>)}</section><section className="card"><h3>对齐设置</h3><Field config={settings.alignment} name="backend" label="对齐后端" choices={['auto','mfa','ctc']} update={update('alignment')}/><Field config={settings.alignment} name="agreement_threshold_sec" label="一致性阈值（秒）" kind="number" update={update('alignment')}/><Field config={settings.alignment} name="minimum_confidence" label="最低置信度" kind="number" update={update('alignment')}/><details><summary>高级配置（保留宿主原始字段）</summary><ConfigTree config={settings.alignment} update={next => setSettings(s => ({...s, alignment: next}))}/></details></section></>}
    {category === '外观与交互' && <section className="card"><h3>阅读与编辑</h3><Field config={settings.preferences} name="theme" label="主题" choices={['system','light','dark']} update={update('preferences')}/><RangeField config={settings.preferences} name="font_size" label="正文字号" min={12} max={24} step={1} update={update('preferences')}/><Field config={settings.preferences} name="send_key" label="发送快捷键" choices={['enter','ctrl-enter']} update={update('preferences')}/><Field config={settings.preferences} name="smooth_stream" label="平滑流式文字" kind="checkbox" update={update('preferences')}/><p className="muted">Shift + Enter 换行 · Ctrl / ⌘ + B 加粗 · Alt + ↑ / ↓ 输入历史 · 中文输入法确认不会发送 · 跟随系统的减少动画设置</p></section>}
    {category === '会话与存储' && <><section className="card"><h3>会话状态</h3><p>{state.sessions.length} 个会话 · {state.sessions.filter(s => s.readOnly).length} 个只读历史 · {Object.values(state.tasks).filter(t => store.running(t.sessionId)?.id === t.id).length} 个后台任务</p><p>新会话恢复上下文及证据，不重放 Praat 执行。旧 SQLite 记录只读保留；在会话侧栏查看、搜索和管理。</p><div className="actions"><button onClick={onClose}>管理会话</button><button disabled={Boolean(busy)} onClick={() => { setBusy('refresh'); void store.initialize().then(() => setNotice('会话与任务状态已刷新')).catch(store.report).finally(() => setBusy('')); }}>刷新宿主记录</button></div></section><section className="card"><h3>数据保护</h3><p>草稿与阅读位置通过宿主保存。附件内容由宿主独立存储；历史只记录元数据，不记录音频 Base64 或 API Key。</p><p className="muted">当前接口不提供导出、批量清空或任意路径访问。没有这些权限的操作不会伪装为可用。</p></section></>}
  </div>{confirmTest && <Modal title="确认最小云端验证" onClose={() => setConfirmTest(undefined)}><p>将通过宿主向当前配置地址发出一次{confirmTest === 'text' ? '文字' : '音频'}验证请求，可能产生服务商费用。不是本地模拟。</p><p className="muted">{targetUrl}</p><button className="primary" onClick={() => void runTest(confirmTest)}>确认验证</button></Modal>}{confirmClose && <Modal title="未保存的设置" onClose={() => setConfirmClose(false)}><p>返回会丢弃未保存更改（包括瞬时 API Key 输入）。</p><button onClick={onClose}>丢弃并返回</button><button className="primary" onClick={() => setConfirmClose(false)}>继续编辑</button></Modal>}</section>;
}
function ModelCapability({boot, config, onManual}: {boot: Bootstrap; config: Config; onManual: () => void}) {
  const capability = knownModel(boot.models, config);
  return <><p className={capability ? 'notice' : 'warning'}>{capability ? `真实元数据：上下文 ${capability.contextWindow.toLocaleString()} / 最大输出 ${capability.maxTokens.toLocaleString()} token` : '此模型能力未知。自动预算不能猜测窗口；请配置真实模型窗口并使用手动模式。'}</p>{!capability && <button onClick={onManual}>切换手动预算</button>}<details><summary>已适配模型（{boot.models.length}）</summary>{boot.models.length ? <Json value={boot.models}/> : <p>宿主尚未提供任何适配模型。可填写模型名并配置手动预算。</p>}</details></>;
}
function ConfigTree({config, update}: {config: Config; update: (config: Config) => void}) {
  return <div className="config-tree">{Object.entries(config).filter(([key]) => !/key|secret|password/i.test(key)).map(([key, value]) => value && typeof value === 'object' && !Array.isArray(value) ? <details key={key}><summary>{key}</summary><ConfigTree config={value as Config} update={v => update({...config,[key]: v})}/></details> : typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? <Field key={key} config={config} name={key} label={key} kind={typeof value === 'boolean' ? 'checkbox' : typeof value === 'number' ? 'number' : 'text'} update={(k,v) => update({...config,[k]: v})}/> : <Json key={key} value={{[key]: value}}/>)}</div>;
}
